CREATE EXTENSION pgcrypto;
ALTER  DEFAULT PRIVILEGES REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;

CREATE OR REPLACE FUNCTION uid() RETURNS INTEGER as $$
	BEGIN
        RETURN current_setting('git.logged_user_id')::INTEGER;
	END;
$$ LANGUAGE plpgsql;
